import React, { useState, useEffect, useRef, useCallback } from 'react';
import { FaEnvelope, FaInstagram } from 'react-icons/fa';
import { X } from 'lucide-react';
import contactInfo from '../config/contactInfo';
import cameraImg from '../assets/canon-camera.png';
import './ContactWidget.css';

/**
 * Floating Contact Widget – Cinematic Camera Object
 * Inspired by professional Canon EOS R-series camera.
 * The camera itself acts as the floating trigger button.
 * Clicking opens a refined contact panel emerging directly from the lens.
 */
const DRAG_THRESHOLD = 5; // px of movement before a press becomes a drag

const ContactWidget = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [isShutterActive, setIsShutterActive] = useState(false);
  const [isRemoved, setIsRemoved] = useState(false);
  const [isLeaving, setIsLeaving] = useState(false);
  const [placement, setPlacement] = useState({ below: false, left: false, shiftX: 0 });
  const widgetRef = useRef(null);
  const triggerRef = useRef(null);
  const shutterTimerRef = useRef(null);
  const offsetRef = useRef({ x: 0, y: 0 });
  const dragRef = useRef(null);
  const suppressClickRef = useRef(false);

  const applyOffset = useCallback((x, y) => {
    offsetRef.current = { x, y };
    if (widgetRef.current) {
      widgetRef.current.style.transform = `translate3d(${x}px, ${y}px, 0)`;
    }
  }, []);

  /* Decide which side the panel should open to, ensuring it never overflows the viewport */
  const computePlacement = useCallback(() => {
    const el = triggerRef.current;
    const widget = widgetRef.current;
    if (!el || !widget) return;
    const rect = el.getBoundingClientRect();
    const vw = window.innerWidth || document.documentElement.clientWidth;
    const vh = window.innerHeight || document.documentElement.clientHeight;

    // Determine target panel width based on viewport size matching CSS system
    const targetW =
      vw <= 340 ? 236 :
      vw <= 375 ? 254 :
      vw <= 414 ? 268 :
      vw <= 600 ? 280 :
      vw <= 820 ? 295 :
      vw <= 1024 ? 310 : 320;
    const panelW = Math.min(targetW, vw - 20);

    // Check vertical space: open below if near top or if landscape has more room below
    const isShortLandscape = vh < 520;
    const spaceAbove = rect.top;
    const spaceBelow = vh - rect.bottom;
    const below = isShortLandscape ? spaceBelow > spaceAbove : spaceAbove < 310;

    // Check horizontal space
    const leftEdgeDefault = rect.right - panelW;
    const rightEdgeLeftAligned = rect.left + panelW;

    let left = false;
    let shiftX = 0;

    if (leftEdgeDefault < 10) {
      if (rightEdgeLeftAligned <= vw - 10) {
        left = true;
      } else {
        // Centered on a small screen: clamp panel within screen bounds
        left = false;
        shiftX = 10 - leftEdgeDefault;
      }
    } else if (rect.right > vw - 10) {
      shiftX = (vw - 10) - rect.right;
    }

    setPlacement({ below, left, shiftX });
  }, []);

  const toggle = useCallback(() => {
    if (suppressClickRef.current) return; // click generated by the end of a drag
    if (shutterTimerRef.current) clearTimeout(shutterTimerRef.current);
    setIsShutterActive(true);
    shutterTimerRef.current = setTimeout(() => setIsShutterActive(false), 260);
    setIsOpen((prev) => {
      if (!prev) computePlacement();
      return !prev;
    });
  }, [computePlacement]);

  const close = useCallback(() => {
    setIsOpen(false);
  }, []);

  /* ── Dragging (pointer events: mouse + touch + pen) ── */
  const handlePointerDown = useCallback((e) => {
    if (e.pointerType === 'mouse' && e.button !== 0) return;
    const widget = widgetRef.current;
    if (!widget) return;
    const rect = widget.getBoundingClientRect();
    const vw = window.innerWidth || document.documentElement.clientWidth;
    const vh = window.innerHeight || document.documentElement.clientHeight;
    const baseLeft = rect.left - offsetRef.current.x;
    const baseTop = rect.top - offsetRef.current.y;
    const edgeMargin = vw <= 360 ? 6 : (vw <= 768 ? 8 : 12);

    dragRef.current = {
      id: e.pointerId,
      moved: false,
      startX: e.clientX,
      startY: e.clientY,
      startOX: offsetRef.current.x,
      startOY: offsetRef.current.y,
      minX: edgeMargin - baseLeft,
      maxX: vw - edgeMargin - rect.width - baseLeft,
      minY: edgeMargin - baseTop,
      maxY: vh - edgeMargin - rect.height - baseTop,
    };

    try {
      e.currentTarget.setPointerCapture(e.pointerId);
    } catch {
      /* ignore */
    }
  }, []);

  const handlePointerMove = useCallback((e) => {
    const d = dragRef.current;
    if (!d || d.id !== e.pointerId) return;
    const dx = e.clientX - d.startX;
    const dy = e.clientY - d.startY;
    if (!d.moved) {
      if (Math.hypot(dx, dy) < DRAG_THRESHOLD) return;
      d.moved = true;
      widgetRef.current?.classList.add('contact-widget--dragging');
      setIsOpen(false);
    }
    const x = Math.min(d.maxX, Math.max(d.minX, d.startOX + dx));
    const y = Math.min(d.maxY, Math.max(d.minY, d.startOY + dy));
    applyOffset(x, y);
  }, [applyOffset]);

  const endDrag = useCallback((e) => {
    const d = dragRef.current;
    if (!d || d.id !== e.pointerId) return;
    try {
      e.currentTarget.releasePointerCapture(e.pointerId);
    } catch {
      /* ignore */
    }
    dragRef.current = null;
    widgetRef.current?.classList.remove('contact-widget--dragging');
    if (d.moved) {
      // The browser fires a click after pointerup; swallow it so a drag never triggers the click
      suppressClickRef.current = true;
      setTimeout(() => {
        suppressClickRef.current = false;
      }, 280);
    }
  }, []);

  /* Keep the camera inside the viewport on resize, screen rotation, or orientation change */
  useEffect(() => {
    const onResize = () => {
      const widget = widgetRef.current;
      if (!widget) return;
      if (isOpen) {
        computePlacement();
      }
      const { x, y } = offsetRef.current;
      if (x === 0 && y === 0) return;
      const rect = widget.getBoundingClientRect();
      const vw = window.innerWidth || document.documentElement.clientWidth;
      const vh = window.innerHeight || document.documentElement.clientHeight;
      const edge = vw <= 360 ? 6 : (vw <= 768 ? 8 : 12);
      let nx = x;
      let ny = y;
      if (rect.left < edge) nx += edge - rect.left;
      if (rect.right > vw - edge) nx -= rect.right - (vw - edge);
      if (rect.top < edge) ny += edge - rect.top;
      if (rect.bottom > vh - edge) ny -= rect.bottom - (vh - edge);
      if (nx !== x || ny !== y) applyOffset(nx, ny);
    };

    window.addEventListener('resize', onResize, { passive: true });
    window.addEventListener('orientationchange', onResize, { passive: true });
    if (window.visualViewport) {
      window.visualViewport.addEventListener('resize', onResize, { passive: true });
    }

    return () => {
      window.removeEventListener('resize', onResize);
      window.removeEventListener('orientationchange', onResize);
      if (window.visualViewport) {
        window.visualViewport.removeEventListener('resize', onResize);
      }
    };
  }, [applyOffset, isOpen, computePlacement]);

  useEffect(() => () => {
    if (shutterTimerRef.current) clearTimeout(shutterTimerRef.current);
  }, []);

  /* ── Remove / hide the widget ── */
  const handleRemove = useCallback((e) => {
    e.stopPropagation();
    setIsOpen(false);
    setIsLeaving(true);
    setTimeout(() => setIsRemoved(true), 240);
  }, []);

  /* Close on Escape key */
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && isOpen) {
        close();
        triggerRef.current?.focus();
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, close]);

  /* Close on click or tap outside */
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (isOpen && widgetRef.current && !widgetRef.current.contains(e.target)) {
        close();
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('touchstart', handleClickOutside, { passive: true });
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('touchstart', handleClickOutside);
    };
  }, [isOpen, close]);

  if (isRemoved) return null;

  return (
    <div
      ref={widgetRef}
      className={`contact-widget${isOpen ? ' contact-widget--open' : ''}${isLeaving ? ' contact-widget--leaving' : ''}`}
      role="region"
      aria-label="Contact Us"
    >
      {/* Remove / hide the widget */}
      <button
        className="cw-remove-btn"
        onClick={handleRemove}
        aria-label="Remove camera widget"
        title="Remove"
        type="button"
      >
        <X size={12} strokeWidth={2.6} aria-hidden="true" />
      </button>

      {/* Trigger button – Realistic Cinema Camera (draggable) */}
      <button
        ref={triggerRef}
        className={`cw-trigger${isShutterActive ? ' cw-trigger--shutter' : ''}`}
        onClick={toggle}
        onPointerDown={handlePointerDown}
        onPointerMove={handlePointerMove}
        onPointerUp={endDrag}
        onPointerCancel={endDrag}
        aria-expanded={isOpen}
        aria-controls="cw-panel"
        aria-label={isOpen ? 'Close contact panel' : 'Open contact panel'}
        type="button"
      >
        <div className="cw-camera-frame">
          <img
            src={cameraImg}
            alt="Ariadne Contact Camera"
            className="cw-camera-img"
            draggable={false}
            loading="eager"
            decoding="async"
          />

          {/* Optical multi-coated lens reflection highlight */}
          <div className="cw-lens-reflection" aria-hidden="true" />

          {/* Shutter pulse / optical aperture flare on click */}
          <div className="cw-lens-aperture-flash" aria-hidden="true" />

          {/* Subtle live tally indicator */}
          <div className="cw-tally-light" aria-hidden="true" />
        </div>
      </button>

      {/* Contact panel – Emerges from the camera lens */}
      <div
        id="cw-panel"
        className={`cw-panel${placement.below ? ' cw-panel--below' : ''}${placement.left ? ' cw-panel--left' : ''}`}
        style={placement.shiftX ? { '--cw-shift-x': `${placement.shiftX}px` } : undefined}
        role="dialog"
        aria-label="Contact Ariadne Productions"
        aria-hidden={!isOpen}
      >
        {/* Header */}
        <div className="cw-header">
          <div className="cw-header-content">
            <span className="cw-header-badge">Ariadne Productions</span>
            <h3 className="cw-header-title">Get in Touch</h3>
          </div>
          <button
            className="cw-close-btn"
            onClick={close}
            aria-label="Close contact dialog"
            type="button"
            tabIndex={isOpen ? 0 : -1}
          >
            <X size={14} strokeWidth={2.2} aria-hidden="true" />
          </button>
        </div>

        {/* Body – Contact links */}
        <div className="cw-body">
          {/* Email */}
          <a
            className="cw-link"
            href={`mailto:${contactInfo.email}`}
            aria-label={`Send email to ${contactInfo.email}`}
            tabIndex={isOpen ? 0 : -1}
          >
            <span className="cw-link-icon cw-link-icon--email" aria-hidden="true">
              <FaEnvelope />
            </span>
            <span className="cw-link-info">
              <span className="cw-link-label">Email Us</span>
              <span className="cw-link-value">{contactInfo.email}</span>
            </span>
            <svg
              className="cw-link-arrow"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <polyline points="9 18 15 12 9 6" />
            </svg>
          </a>

          {/* Instagram */}
          <a
            className="cw-link"
            href={contactInfo.instagram.url}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={`Visit Instagram @${contactInfo.instagram.handle}`}
            tabIndex={isOpen ? 0 : -1}
          >
            <span className="cw-link-icon cw-link-icon--instagram" aria-hidden="true">
              <FaInstagram />
            </span>
            <span className="cw-link-info">
              <span className="cw-link-label">Instagram</span>
              <span className="cw-link-value">@{contactInfo.instagram.handle}</span>
            </span>
            <svg
              className="cw-link-arrow"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden="true"
            >
              <polyline points="9 18 15 12 9 6" />
            </svg>
          </a>

        </div>

        {/* Footer info */}
        <div className="cw-footer">
          <p className="cw-footer-loc">📍 {contactInfo.location}</p>
          <p className="cw-footer-text">Cinematic Photography & Visual Arts</p>
        </div>
      </div>
    </div>
  );
};

export default ContactWidget;
